fieldLayouts:
  e1716d10-712a-4699-862c-ef7c2ff2dafa:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: ca58395f-6040-4801-9a76-8fa8538f3b73 # Redactor Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: be0b2700-cb92-4ca3-8d28-82cef3d6c587 # Plain Text Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 2'
        sortOrder: 2
handle: default
hasTitleField: true
name: Default
section: 45da72e5-9e60-4931-b242-57b32130c128 # Channel
sortOrder: 1
titleFormat: '{entry.postDate|date("l j M Y")}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
