defaultPlacement: end
fieldLayouts:
  8fd234db-07dc-481f-a851-b8df1a62b150:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: testCategoryGroup
name: 'Test Category Group'
siteSettings:
  0fa3ee94-9804-4d1d-a084-479bd7516a07: # Craft CMS Development
    hasUrls: true
    template: null
    uriFormat: 'test-category-group/{slug}'
structure:
  maxLevels: null
  uid: 58c63af6-8a35-4458-bea8-a89e5001d259
