baseUrl: $OTHER_SITE_URL
enabled: true
handle: otherSite
hasUrls: true
language: en-US
name: 'Other Site'
primary: false
siteGroup: 55ac92e4-c136-4544-ba73-0d26ba2a8e8b # Default Site Group
sortOrder: 2
