fieldLayouts:
  f9e84931-349f-49dc-97e3-5e42529157a9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3060c228-83d3-4c22-ac07-7f969baa3afb
            warning: null
            width: 100
        name: Content
        uid: d7912da1-94e4-4ba9-b496-10d4ce19acdb
fs: memberPhotosLocal
handle: memberPhotos
name: 'Member Photos'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
