fieldLayouts:
  76fd7950-743f-499b-94ef-92cb6b71192e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c78b1b74-db92-4937-bf9b-4174697a073a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 16a2c535-5586-4442-999b-8037b030ecb1
        userCondition: null
fs: myFilesystem
handle: myVolume
name: 'My Volume'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
