dateModified: 1656471151
email:
  fromEmail: tim@craftcms.com
  fromName: 'Craft 4 Development'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3ec516bb-26e7-4f7f-bbaa-2327c6b062ba: Common # Common
    a351c588-db89-456c-aa4b-ebe1e076ff1c: Dummy # Dummy
    b1a41433-0843-4dab-8d06-a2c8101a80d5: New # New
    c5d66fb0-eb02-491b-af82-0ebd072ea6f4: 'Craft 4 Development' # Craft 4 Development
    f67c7c9b-cf1b-4839-9752-db69cbfd593f: 'Craft 4 Development' # Craft 4 Development
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  commerce:
    edition: lite
    enabled: true
    licenseKey: CNR6ABNLD9BZ4F1C0TFU9MYX
    schemaVersion: 4.0.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: 'Craft 4 Development'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
