dateModified: 1656466095
email:
  fromEmail: tim@craftcms.com
  fromName: 'Craft 3 Development'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    7de95332-c7ec-4173-9e9c-ba0d879267aa: 'Craft 3 Development' # Craft 3 Development
    8cec2af1-2ba5-4520-aed9-6953a501cfbe: 'Craft 3 Development' # Craft 3 Development
    41728021-347e-4735-80b2-4f1c2cd63036: Common # Common
system:
  edition: pro
  live: true
  name: 'Craft 3 Development'
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
